# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Install Poetry Action
on: [push]
jobs:
  poetry_actions:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: poetry install

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
      
    - run: ~/.local/bin/poetry run task test
    - run: ~/.local/bin/poetry run task lint
    - run: ~/.local/bin/poetry run task formatter
    - run: ~/.local/bin/poetry run task security
