# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Poetry actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
      
    - name: Install dependencies
      run: poetry install --no-root --no-interaction

  tests:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app

    steps:
    - name: Run test  
      run: ~/.local/bin/poetry run task test
    
    - name: Run lint
      run: ~/.local/bin/poetry run task lint

    - name: Run formatter
      run: ~/.local/bin/poetry run task formatter

    - name: Run security
      run: ~/.local/bin/poetry run task security

  unittests:
    needs: tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app

    steps:
    - name: Run test  
      run: ~/.local/bin/poetry run task test
    
