# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Install Poetry Action
on: [push]
jobs:
  poetry_actions:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app
        
    steps:
      - run: poetry run task test
      - run: poetry run task lint
      - run: poetry run task formatter
      - run: poetry run task security
